# Generated by Django 5.2.6 on 2025-09-16 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('outro', 'Outro')], max_length=20)),
                ('data_programada', models.DateField()),
                ('status', models.CharField(default='ativo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('nis', models.CharField(max_length=11, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(max_length=20, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('integrantes_familia', models.IntegerField(default=1)),
                ('telefone', models.CharField(max_length=15)),
                ('grupo', models.CharField(choices=[('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('qrcode', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateTimeField(auto_now_add=True)),
                ('validada', models.BooleanField(default=False)),
                ('entregador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='system.grupoentrega')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='system.pessoa')),
            ],
        ),
    ]
