# Generated by Django 5.2.6 on 2025-09-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='validade',
        ),
        migrations.AddField(
            model_name='grupoentrega',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
